### ISSUE TITLE
install Error

### ISSUE THREAD

**Issue by qliugithub** [itsvenu/ALPS#2]
When installing, I have the following errors and failed.
```{r}
Error in unpackPkgZip(foundpkgs[okp, 2L], foundpkgs[okp, 1L], lib, libs_only,  : 
  ERROR: failed to lock directory ‘D:\swRJ\R-3.6.1\R-3.6.1\library’ for modifying
Try removing ‘D:\swRJ\R-3.6.1\R-3.6.1\library/00LOCK’
此外: Warning message:
package ‘ALPS’ is not available (for R version 3.6.1) 
```

**Comment by itsvenu** [comment]
Did you update `Bioc` version to 3.10?

What's the result of `BiocManager::version()`?

You can update with `BiocManager::install(version="3.10")`.

Let me know if that works.
